server:
    port: ${PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-service.up.railway.app/eureka/}
  instance:
    hostname: ${HOSTNAME:gateway-server.up.railway.app}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-client
          uri: https://microservice-client.up.railway.app/
          predicates:
            - Path=/api/clients/**
        - id: microservice-webs
          uri: https://microservice-webs.up.railway.app/
          predicates:
            - Path=/api/developers/**, /api/webs-invoices/**, /api/webpages/**
      discovery:
        locator:
          enabled: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true

