server:
    port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: microservice-client
              uri: lb://microservice-client
              filters:
                - PrefixPath=/api
              predicates:
                - Path=/clients/**
            - id: microservice-clothes
              uri: lb://microservice-clothes
              filters:
                - PrefixPath=/api
              predicates:
                - Path=/categories/**, /clothes-invoices/**, /categories/**, /products/**
            - id: microservice-webs
              uri: lb://microservice-webs
              filters:
                - PrefixPath=/api
              predicates:
                - Path=/developers/**, /webs-invoices/**, /webpages/*
      discovery:
        locator:
          enabled: true

