server:
    port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-client
          uri: lb://MICROSERVICE-CLIENT
          predicates:
            - Path=/api/clients/**
        - id: microservice-clothes
          uri: lb://MICROSERVICE-CLOTHES
          predicates:
            - Path=/api/categories/**, /api/clothes-invoices/**, /api/categories/**, /api/products/**
        - id: microservice-webs
          uri: lb://MICROSERVICE-WEBS
          predicates:
            - Path=/api/developers/**, /api/webs-invoices/**, /api/webpages/**
