server:
    port: ${PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-service-production.up.railway.app/eureka/}
  instance:
    hostname: ${HOSTNAME:gateway-service-production.up.railway.app}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: microservice-client
              uri: lb://microservice-client
              predicates:
                - Path=/api/clients/**
            - id: microservice-clothes
              uri: lb://microservice-clothes
              predicates:
                - Path=/api/categories/**, /api/clothes-invoices/**, /api/products/**
            - id: microservice-webs
              uri: lb://microservice-webs
              predicates:
                - Path=/api/developers/**, /api/webs-invoices/**, /api/webpages/*
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true

