server:
  port: ${PORT:0}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-wandering-water-acfo8u2p-pooler.sa-east-1.aws.neon.tech:5432/webs?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_DmJql9HWL7sN}
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-service-production.up.railway.app/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: ${HOSTNAME:microservice-webs-production.up.railway.app}