server:
  port: ${PORT:8001}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://shuttle.proxy.rlwy.net:15561/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:XlihnIDCeRHlbdSTqLQwVNKPMDcuLmTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-service.up.railway.app/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: ${HOSTNAME:microservice-client}

