server:
  port: 8003
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webs?useSSL=false
    username: postgres
    password: '8888'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update