spring:
  application:
    name: microservice-client
  datasource:
    url: jdbc:mysql://localhost:3306/client
    username: root
    password: '0000'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:0}



